services:
  gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JWT_SECRET: secret
    depends_on:
      - auth-service
      - tecnico-service

  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: secret
    depends_on:
      - auth-db

  tecnico-service:
    build: ./tecnico
    container_name: tecnico-service
    ports:
      - "8082:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tecnico-db:5432/tecnicodb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: secret
    depends_on:
      - tecnico-db

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authdb
    volumes:
      - auth_data:/var/lib/postgresql/data

  tecnico-db:
    image: postgres:16
    container_name: tecnico-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tecnicodb
    volumes:
      - tecnico_data:/var/lib/postgresql/data

volumes:
  auth_data:
  tecnico_data:
